<section class="completed">
	<h2>Verdict</h2>
	<dl>
	<?php foreach ($state->goals as $goal): ?>
		<?php if (($answer = $goal->answer($state)) || $state->facts[$goal->name] != STATE_UNDEFINED): ?>
			<dt>
					<p><?=$goal->description?></p>
					<?php if ($answer->youtube): ?>
					<iframe width="420" height="315" src="https://www.youtube.com/embed/<?=$answer->youtube?>"></iframe> 
					<?php endif ?>
			</dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name] . '</pre>';
				?></dd>
			<?php endif ?>
	<?php endforeach ?>
	</dl>
</section>
