<section class="question">
	<p><?=$state->substitute_variables($question->description, ['Template', 'html'])?></p>

	<?php if ($question->audio_file): ?>
		<audio controls controlsList="nodownload">
			<source src="<?=$question->audio_file?>" type="audio/mpeg">
		</audio>
	<?php endif ?>

	<ol class="options">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="radio" name="answer" value="<?=_encode($option->consequences)?>">
				<?=$state->substitute_variables($option->description, ['Template', 'html'])?>
			</label>
		</li>
		<?php endforeach ?>
		<?php if($question->skippable): ?>
		<li class="skip-option">
			<label>
				<input type="radio" name="answer" value="<?=_encode(array())?>">
				I don't know
			</label>
		</li>
		<?php endif ?>
	</ol>

	<button type="submit">Continue…</button>
</section>
